const productData = [
	{
		id: 1,
		name: "Ic QFN28",
		price: 250,
		img: "img/componentes/componentes/450_450-QFN28.png",
		color: "Negro",
		category: "remeras",
		description: "100%-algodon",
		envio: 300,
	},
	{
		id: 2,
		name: "Remera negra",
		price: 2200,
		img: "img/componentes/componentes/450_450-STM32F103C8T6_1.png",
		color: "Negro",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 3,
		name: "Remera roja",
		price: 2200,
		img: "img/componentes/componentes/450_450-TQFP32.png",
		color: "Rojo",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 4,
		name: "Remera verde",
		price: 2200,
		img: "img/componentes/componentes/450_450-TQFP441.png",
		color: "Verde",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 5,
		name: "Gorra negra",
		price: 1200,
		img: "img/productos/gorras/gorra-negra.png",
		color: "Negro",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 6,
		name: "Gorra roja",
		price: 1200,
		img: "img/productos/gorras/gorra-roja.png",
		color: "Rojo",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 7,
		name: "Gorra amarilla",
		price: 1200,
		img: "img/productos/gorras/gorra-amarilla.png",
		color: "Amarillo",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 8,
		name: "Gorra gris",
		price: 1200,
		img: "img/productos/gorras/gorra-gris.png",
		color: "Gris",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 9,
		name: "Taza blanca",
		price: 500,
		img: "img/productos/tazas/tazaBlanca.PNG",
		color: "Blanco",
		category: "tazas",
		description: "Ceramica",
		envio: 2000,
	},
	{
		id: 10,
		name: "Taza negra",
		price: 500,
		img: "img/productos/tazas/tazaNegra.PNG",
		color: "Negro",
		category: "tazas",
		description: "Ceramica",
		envio: 2000,
	},
	{
		id: 11,
		name: "WHEY",
		price: 5500,
		img: "img/componentes/componentes/arduino-uno.jpg",
		category: "suplementos",
		description: "Proteina",
		type: "Proteina",
		envio: 2000,
	},
	{
		id: 12,
		name: "Universal",
		price: 6000,
		img: "img/componentes/componentes/kit-arduino.jpg",
		category: "suplementos",
		description: "Creatina",
		type: "Creatina",
		envio: 2000,
	},
	{
		id: 13,
		name: "BCAA",
		price: 4000,
		img: "img/componentes/componentes/mini-servo.png",
		category: "suplementos",
		description: "Aminoacidos",
		type: "Aminoacidos",
		envio: 2000,
	},
	{
		id: 14,
		name: "Push/Pull/Legs",
		price: 4500,
		img: "img/productos/rutinas/rutina-1.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 15,
		name: "PHAT",
		price: 4500,
		img: "img/productos/rutinas/rutina-2.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 16,
		name: "Powerbuilding",
		price: 4500,
		img: "img/productos/rutinas/rutina-3.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 17,
		name: "Upper/Lower",
		price: 4500,
		img: "img/productos/rutinas/rutina-4.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 18,
		name: "Fullbody-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-5.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 19,
		name: "Upper/Lower-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-6.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 20,
		name: "Push/Pull-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-7.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
];

