const productData = [
	{
		id: 1,
		name: "Ic QFN28",
		price: 250,
		img: "img/componentes/componentes/450_450-QFN28.png",
		color: "Negro",
		category: "remeras",
	
		envio: 300,
	},
	{
		id: 2,
		name: "STM32",
		price: 2200,
		img: "img/componentes/componentes/450_450-STM32F103C8T6_1.png",
		color: "Negro",
		category: "remeras",
	
		envio: 2000,
	},
	{
		id: 3,
		name: "esp",
		price: 2200,
		img: "img/componentes/componentes/450_450-TQFP32.png",
		color: "Negro",
		category: "remeras",

		envio: 2000,
	},
	{
		id: 4,
		name: "esp",
		price: 2200,
		img: "img/componentes/componentes/450_450-TQFP441.png",
		color: "Negro",
		category: "remeras",

		envio: 2000,
	},
	{
		id: 5,
		name: "esp",
		price: 1200,
		img: "img/componentes/componentes/esp8266.jpeg",
		color: "Negro",
		category: "gorras",

		envio: 2000,
	},
	{
		id: 6,
		name: "esp",
		price: 1200,
		img: "img/componentes/componentes/esp8266x2.jpeg",
		color: "Negro",
		category: "gorras",

		envio: 2000,
	},
	{
		id: 7,
		name: "ic1",
		price: 1200,
		img: "img/componentes/componentes/esp8266-mini.jpeg",
		color: "Negro",
		category: "gorras",

		envio: 2000,
	},
	{
		id: 8,
		name: "ic2",
		price: 1200,
		img: "img/componentes/componentes/esp8266-d1.jpeg",
		color: "Negro",
		category: "gorras",

		envio: 2000,
	},
	{
		id: 9,
		name: "stm",
		price: 500,
		img: "img/componentes/componentes/images.png",
		color: "Negro",
		category: "tazas",

		envio: 2000,
	},
	{
		id: 10,
		name: "stm",
		price: 500,
		img: "img/componentes/componentes/stm32.jpeg",
		color: "Negro",
		category: "tazas",

		envio: 2000,
	},
	{
		id: 11,
		name: "WHEY",
		price: 5500,
		img: "img/componentes/componentes/arduino-uno.jpg",
		category: "suplementos",
		description: "electro",
		type: "Arduino UNO",
		envio: 2000,
	},
	{
		id: 12,
		name: "Arduino",
		price: 6000,
		img: "img/componentes/componentes/kit-arduino.jpg",
		category: "suplementos",
		description: "electro",
		type: "kit arduino",
		envio: 2000,
	},
	{
		id: 13,
		name: "Servo",
		price: 4000,
		img: "img/componentes/componentes/mini-servo.png",
		category: "suplementos",
		description: "electro",
		type: "Servo motor",
		envio: 2000,
	},
	{
		id: 14,
		name: " 50% off Placas de desarrollo STM",
		price: 1550,
		img: "img/componentes/componentes/images.png",
		duration: "3 dias",
		category: "rutinas",

		envio: 450,
	},
	{
		id: 15,
		name: "50% off Placas de desarrollo ESP8266",
		price: 2800,
		img: "img/componentes/componentes/esp8266.png",
		duration: "3 dias",
		category: "rutinas",

		envio: 450,
	},
	{
		id: 16,
		name: "50% off Placas de desarrollo Arduino",
		price: 1850,
		img: "img/componentes/componentes/ardu-nano.png",
		duration: "3 dias",
		category: "rutinas",

		envio: 450,
	},
	{
		id: 17,
		name: " 15% off Nodemcu",
		price: 4500,
		img: "img/componentes/componentes/nodemcu.jpeg",
		duration: "3 dias",
		category: "rutinas",

		envio: 0,
	},
	{
		id: 18,
		name: "30% off Sensores",
		price: 7500,
		img: "img/componentes/componentes/sensor-MPX5010DP.jpg",
		duration: "3 dias",
		category: "rutinas",
		envio: 0,
	},
	{
		id: 19,
		name: "15% off LCD",
		price: 2700,
		img: "img/componentes/componentes/lcd-16x2.png",
		duration: "3 dias",
		category: "rutinas",
		envio: 450,
	},
	{
		id: 20,
		name: "10% off LED",
		price: 15,
		img: "img/componentes/componentes/led-pira.jpg",
		duration: "3 dias",
		category: "rutinas",
		envio: 100,
	},
];

